# Dependabot Configuration for Crown & Barrel iOS App
# This file configures automated dependency updates

version: 2
updates:
  # Enable version updates for Swift Package Manager
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "csummers-dev"
    assignees:
      - "csummers-dev"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "swift"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      swift-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "csummers-dev"
    assignees:
      - "csummers-dev"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for npm (if using any Node.js tools)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "csummers-dev"
    assignees:
      - "csummers-dev"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Docker (if using containers)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "csummers-dev"
    assignees:
      - "csummers-dev"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for Bundler (if using Ruby gems)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "csummers-dev"
    assignees:
      - "csummers-dev"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
    ignore:
      # Ignore major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
