name: CrownAndBarrel
options:
  deploymentTarget:
    iOS: "18.0"  # Updated to iOS 18.0 to match available simulators
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: 6.28.0
targets:
  CrownAndBarrel:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: AppResources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.crownandbarrel.app
        INFOPLIST_FILE: AppResources/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 18.0  # Updated to iOS 18.0 to match available simulators
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: 1
        # Code signing configuration
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: G7Z5DDPMSL
    dependencies:
      - package: ZIPFoundation
      - package: GRDB
    info:
      path: AppResources/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        CFBundleDisplayName: "Crown & Barrel"

  CrownAndBarrelTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Unit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 18.0  # Updated to iOS 18.0 to match available simulators
    dependencies:
      - target: CrownAndBarrel

  CrownAndBarrelUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 18.0  # Updated to iOS 18.0 to match available simulators
    dependencies:
      - target: CrownAndBarrel


