name: GoodWatch
options:
  deploymentTarget:
    iOS: "17.0"
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
targets:
  GoodWatch:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: AppResources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.goodwatch.app
        INFOPLIST_FILE: AppResources/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: ZIPFoundation
    info:
      path: AppResources/Info.plist

  GoodWatchTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Unit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
    dependencies:
      - target: GoodWatch

  GoodWatchUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
    dependencies:
      - target: GoodWatch


