name: CrownAndBarrel
options:
  deploymentTarget:
    iOS: "17.0"
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.19
targets:
  CrownAndBarrel:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: AppResources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.crownandbarrel.app
        INFOPLIST_FILE: AppResources/Info.plist
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: 1
    dependencies:
      - package: ZIPFoundation
    info:
      path: AppResources/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        CFBundleDisplayName: "Crown & Barrel"

  CrownAndBarrelTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/Unit
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
    dependencies:
      - target: CrownAndBarrel

  CrownAndBarrelUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/UITests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        IPHONEOS_DEPLOYMENT_TARGET: 17.0
    dependencies:
      - target: CrownAndBarrel


