name: iOS CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install xcpretty
        run: |
          gem install xcpretty --no-document

      - name: Run Unit Tests (only)
        run: |
          xcodebuild -project CrownAndBarrel.xcodeproj \
                     -scheme CrownAndBarrel \
                     -destination 'platform=iOS Simulator,name=iPhone 16' \
                     -only-testing:CrownAndBarrelTests \
                     test | xcpretty

  ui-tests:
    name: UI Tests (hardened)
    runs-on: macos-14
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install xcpretty
        run: |
          gem install xcpretty --no-document

      - name: Run UI Tests with retries and no parallelization
        run: |
          xcodebuild -project CrownAndBarrel.xcodeproj \
                     -scheme CrownAndBarrel \
                     -destination 'platform=iOS Simulator,name=iPhone 16' \
                     -only-testing:CrownAndBarrelUITests \
                     -retry-tests-on-failure \
                     -test-iterations 2 \
                     -parallel-testing-enabled NO \
                     -maximum-concurrent-test-simulator-destinations 1 \
                     test | xcpretty


