name: iOS CI (Fast Feedback)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# Fast feedback pipeline for all branches - runs essential tests only

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup iOS Environment
        uses: ./.github/actions/setup-ios-environment
        with:
          xcode-version: "26.0.0"
          install-xcodegen: 'true'
          install-swiftlint: 'false'
          install-xcpretty: 'true'
          cache-key-suffix: 'unit-tests'

      - name: Cache Swift Packages
        uses: ./.github/actions/cache-dependencies
        with:
          cache-type: 'swift-packages'
          cache-key: ${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ hashFiles('**/Package.swift') }}
            latest
          cache-suffix: 'unit-tests'

      - name: Run Unit Tests (only)
        run: |
          echo "Running unit tests with simple configuration..."
          xcodebuild test \
            -project CrownAndBarrel.xcodeproj \
            -scheme CrownAndBarrel \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=26.0" \
            -only-testing:CrownAndBarrelTests \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
            VALID_ARCHS="arm64" \
            ARCHS="arm64" \
            -resultBundlePath TestResults.xcresult \
            | xcpretty

# Fast feedback pipeline - unit tests only for quick validation
# Full UI tests run in main CI pipeline (ci.yml) for main/develop branches


