name: iOS CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install xcpretty
        run: |
          gem install xcpretty --no-document

      - name: Install XcodeGen and generate project
        run: |
          if ! command -v xcodegen &> /dev/null; then
            brew install xcodegen
          fi
          xcodegen generate

      - name: Run Unit Tests (only)
        run: |
          # Target iPhone 16 Pro with iOS 26.0 specifically for unit tests
          echo "Running unit tests on iPhone 16 Pro with iOS 26.0..."
          xcodebuild -project CrownAndBarrel.xcodeproj \
                     -scheme CrownAndBarrel \
                     -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=26.0" \
                     -only-testing:CrownAndBarrelTests \
                     test | xcpretty

  ui-tests:
    name: UI Tests (hardened)
    runs-on: macos-14
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Install xcpretty
        run: |
          gem install xcpretty --no-document

      - name: Install XcodeGen and generate project
        run: |
          if ! command -v xcodegen &> /dev/null; then
            brew install xcodegen
          fi
          xcodegen generate

      - name: Run UI Tests with retries and no parallelization
        run: |
          # Target iPhone 16 Pro with iOS 26.0 specifically for UI tests
          echo "Running UI tests on iPhone 16 Pro with iOS 26.0..."
          xcodebuild -project CrownAndBarrel.xcodeproj \
                     -scheme CrownAndBarrel \
                     -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=26.0" \
                     -only-testing:CrownAndBarrelUITests \
                     -retry-tests-on-failure \
                     -test-iterations 2 \
                     -parallel-testing-enabled NO \
                     -maximum-concurrent-test-simulator-destinations 1 \
                     test | xcpretty


