name: iOS CI (Fast Feedback)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'README.md'
      - 'CHANGELOG.md'

# Fast feedback pipeline for all branches - runs essential tests only

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup iOS Environment
        uses: ./.github/actions/setup-ios-environment
        with:
          xcode-version: "latest-stable"
          install-xcodegen: 'true'
          install-swiftlint: 'false'
          install-xcpretty: 'true'
          cache-key-suffix: 'unit-tests'

      - name: Cache Swift Packages
        uses: ./.github/actions/cache-dependencies
        with:
          cache-type: 'swift-packages'
          cache-key: ${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ hashFiles('**/Package.swift') }}
            latest
          cache-suffix: 'unit-tests'

      - name: Run Unit Tests (only)
        run: |
          # Find the best available iOS simulator for unit tests
          echo "Looking for available iOS simulators for unit tests..."
          
          # Check for iPhone 16 Pro with iOS 18.2 first (preferred)
          if xcodebuild -showdestinations -scheme CrownAndBarrel -project CrownAndBarrel.xcodeproj 2>/dev/null | grep "platform:iOS Simulator" | grep "iPhone 16 Pro" | grep -q "18.2"; then
            DESTINATION="platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2"
            echo "✅ Found iPhone 16 Pro with iOS 18.2 - using preferred target for unit tests"
          # Fallback to any iPhone with iOS 18.1
          elif xcodebuild -showdestinations -scheme CrownAndBarrel -project CrownAndBarrel.xcodeproj 2>/dev/null | grep "platform:iOS Simulator" | grep "iPhone" | grep -q "18.1"; then
            # Get first available iPhone with iOS 18.1
            IPHONE_18_LINE=$(xcodebuild -showdestinations -scheme CrownAndBarrel -project CrownAndBarrel.xcodeproj 2>/dev/null | grep "platform:iOS Simulator" | grep "iPhone" | grep "18.1" | head -1)
            IPHONE_NAME=$(echo "$IPHONE_18_LINE" | grep -o 'name:[^,]*' | cut -d: -f2)
            DESTINATION="platform=iOS Simulator,name=$IPHONE_NAME,OS=18.1"
            echo "✅ Found $IPHONE_NAME with iOS 18.1 - using fallback target for unit tests"
          # Fallback to iPhone 15 Pro with iOS 17.x
          elif xcodebuild -showdestinations -scheme CrownAndBarrel -project CrownAndBarrel.xcodeproj 2>/dev/null | grep "platform:iOS Simulator" | grep "iPhone 15 Pro"; then
            DESTINATION="platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5"
            echo "✅ Using iPhone 15 Pro with iOS 17.5 - reliable fallback target for unit tests"
          else
            echo "❌ No suitable iOS simulators found, skipping unit tests"
            exit 0
          fi
          
          echo "Running unit tests with destination: $DESTINATION"
          xcodebuild -project CrownAndBarrel.xcodeproj \
                     -scheme CrownAndBarrel \
                     -destination "$DESTINATION" \
                     -only-testing:CrownAndBarrelTests \
                     test | xcpretty

# Fast feedback pipeline - unit tests only for quick validation
# Full UI tests run in main CI pipeline (ci.yml) for main/develop branches


